# Generated by Django 6.0.2 on 2026-02-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_duties_alter_teacher_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='duties',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
