# Generated by Django 6.0.2 on 2026-02-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_teacher_duties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening')], max_length=20)),
                ('rooms_required', models.PositiveIntegerField()),
                ('teachers_per_room', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='id',
            new_name='teacher_id',
        ),
    ]
