# Generated by Django 6.0.2 on 2026-02-22 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_teacher_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('morning_start', models.TimeField()),
                ('morning_end', models.TimeField()),
                ('evening_start', models.TimeField()),
                ('evening_end', models.TimeField()),
                ('exam_duration', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='exam',
            name='date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_name',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='rooms_required',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='teachers_per_room',
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=10)),
                ('total_positions', models.IntegerField()),
                ('filled_positions', models.IntegerField(default=0)),
                ('exam_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.examdate')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.slot')),
            ],
        ),
    ]
