# Generated by Django 6.0.2 on 2026-02-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_examdate_remove_exam_date_remove_exam_exam_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='duties',
        ),
        migrations.AddField(
            model_name='teacher',
            name='max_hours',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
