# Generated by Django 6.0.2 on 2026-02-24 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_alter_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdate',
            name='booking_deadline',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 24, 20, 8, 1, 472859, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
