# Generated by Django 6.0.2 on 2026-02-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_examdate_booking_deadline'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('exam_date', 'shift')},
        ),
    ]
