# Generated by Django 6.0.2 on 2026-03-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_alter_slot_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examdate',
            name='exam_duration',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='max_hours',
        ),
        migrations.AddField(
            model_name='examdate',
            name='total_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='duties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='relaxation_duties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='relaxation_hours',
            field=models.IntegerField(default=0),
        ),
    ]
