# Generated by Django 6.0.2 on 2026-03-22 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_remove_examdate_exam_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='total_positions',
        ),
    ]
