# Generated by Django 6.0.2 on 2026-03-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_remove_slot_total_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='total_positions',
            field=models.IntegerField(default=2),
        ),
    ]
