# Generated by Django 6.0.2 on 2026-03-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0015_slot_total_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='total_positions',
            field=models.IntegerField(),
        ),
    ]
