# Generated by Django 6.0.2 on 2026-03-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0016_alter_slot_total_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='total_positions',
            field=models.IntegerField(default=0),
        ),
    ]
