# Generated by Django 6.0.2 on 2026-03-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0017_alter_slot_total_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdate',
            name='evening_slots',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='examdate',
            name='morning_slots',
            field=models.IntegerField(default=1),
        ),
    ]
