# Generated by Django 6.0.2 on 2026-03-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0018_examdate_evening_slots_examdate_morning_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examdate',
            name='evening_slots',
        ),
        migrations.RemoveField(
            model_name='examdate',
            name='morning_slots',
        ),
        migrations.AlterField(
            model_name='slot',
            name='total_positions',
            field=models.IntegerField(),
        ),
    ]
