# Generated by Django 6.0.2 on 2026-04-05 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0019_remove_examdate_evening_slots_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('booked', 'Slot Booked'), ('cancelled', 'Slot Cancelled'), ('auto_assigned', 'Auto Assigned')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
