# Generated by Django 6.0.2 on 2026-04-14 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0022_teacher_email_teacher_otp_teacher_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='preferred_shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('none', 'No Preference')], default='none', max_length=10),
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
        ),
    ]
