# Generated by Django 6.0.2 on 2026-04-16 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0024_department_teacher_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='faculty_id',
            field=models.CharField(default=123, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TeacherUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Unavailable Date',
                'verbose_name_plural': 'Unavailable Dates',
                'unique_together': {('teacher', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='TeacherAvailability',
        ),
    ]
