# Generated by Django 6.0.2 on 2026-04-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0025_teacher_faculty_id_teacherunavailability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='faculty_id',
            field=models.CharField(max_length=50),
        ),
    ]
