# Generated by Django 6.0.2 on 2026-04-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0026_alter_teacher_faculty_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='faculty_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
