# Generated by Django 6.0.2 on 2026-04-17 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0027_alter_teacher_faculty_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255)),
                ('paper_code', models.CharField(max_length=100)),
                ('students', models.IntegerField()),
                ('session', models.CharField(max_length=10)),
                ('exam_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='teachers.examdate')),
            ],
        ),
    ]
