# Generated by Django 6.0.2 on 2026-04-17 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0028_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='exam_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='teachers.examdate'),
        ),
    ]
