# Generated by Django 6.0.2 on 2026-04-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0030_deputysuperintendent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='paper_code',
        ),
    ]
