# Generated by Django 6.0.2 on 2026-05-08 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0031_remove_exam_paper_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_sent', to='teachers.teacher')),
                ('requester_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_as_requester', to='teachers.booking')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to='teachers.teacher')),
                ('target_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_as_target', to='teachers.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
